language: node_js
node_js:
    - "7.6.0"
cache: yarn
services:
    - mongodb
notifications:
  slack: team4159:wKcqUG4VCrh6yzknuOcvJaf9
script:
    - make deps
    - make build
    - make lint
    - make test
after_success:
   - bash <(curl -s https://codecov.io/bash)
