language: node_js
node_js:
  - "5"
install:
  - "npm install --production"
  - "npm install mocha"
  - "npm install chai"
  - "npm install istanbul"
script:
  - "npm run cover"
after_success:
  - bash <(curl -s https://codecov.io/bash)
