language: node_js
node_js:
    - "7.6"
services:
    - mongodb
env:
    - MONGODB_URI=mongodb://localhost/test
notifications:
  slack: team4159:wKcqUG4VCrh6yzknuOcvJaf9
install:
    - npm install -g yarn
    - yarn config set cache ~/.yarn-cache
    - yarn
script:
    - npm run cover
after_success:
    - bash <(curl -s https://codecov.io/bash)
